name: Checkout Without Action

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clone Repository
        run: |
          git clone https://github.com/Softwaresingham/GITHUB_ACTIONS.git
          cd GITHUB_ACTIONS
          ls -lrt
        
