name: Checkout With Action

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Verify
        run: ls -lrt
        
