name: Check Installed Tools

on:
  push

jobs:
  check-tools:

    runs-on: ubuntu-latest

    steps:

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Check NodeJS
        run: node -v

      - name: Check NPM
        run: npm -v

      - name: Check Docker
        run: docker --version

      - name: Check Kubectl
        run: kubectl version --client
